// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameFinishedMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GameFinishedMessage.proto</summary>
public static partial class GameFinishedMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for GameFinishedMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameFinishedMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlHYW1lRmluaXNoZWRNZXNzYWdlLnByb3RvIlwKEkdhbWVGaW5pc2hlZFBs",
          "YXllchIRCglwbGF5ZXJfaWQYASABKAkSDAoEa2V5cxgCIAEoDRINCgVnb2xk",
          "cxgDIAEoDRIWCg5nb2xkc19pbl9ob3VzZRgEIAEoDSJNChNHYW1lRmluaXNo",
          "ZWRNZXNzYWdlEhMKC3JvdW5kX2NvdW50GAEgASgNEiEKBHJhbmsYAiADKAsy",
          "Ey5HYW1lRmluaXNoZWRQbGF5ZXJiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GameFinishedPlayer), global::GameFinishedPlayer.Parser, new[]{ "PlayerId", "Keys", "Golds", "GoldsInHouse" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GameFinishedMessage), global::GameFinishedMessage.Parser, new[]{ "RoundCount", "Rank" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GameFinishedPlayer : pb::IMessage<GameFinishedPlayer>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GameFinishedPlayer> _parser = new pb::MessageParser<GameFinishedPlayer>(() => new GameFinishedPlayer());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GameFinishedPlayer> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameFinishedMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameFinishedPlayer() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameFinishedPlayer(GameFinishedPlayer other) : this() {
    playerId_ = other.playerId_;
    keys_ = other.keys_;
    golds_ = other.golds_;
    goldsInHouse_ = other.goldsInHouse_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameFinishedPlayer Clone() {
    return new GameFinishedPlayer(this);
  }

  /// <summary>Field number for the "player_id" field.</summary>
  public const int PlayerIdFieldNumber = 1;
  private string playerId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PlayerId {
    get { return playerId_; }
    set {
      playerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "keys" field.</summary>
  public const int KeysFieldNumber = 2;
  private uint keys_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Keys {
    get { return keys_; }
    set {
      keys_ = value;
    }
  }

  /// <summary>Field number for the "golds" field.</summary>
  public const int GoldsFieldNumber = 3;
  private uint golds_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Golds {
    get { return golds_; }
    set {
      golds_ = value;
    }
  }

  /// <summary>Field number for the "golds_in_house" field.</summary>
  public const int GoldsInHouseFieldNumber = 4;
  private uint goldsInHouse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GoldsInHouse {
    get { return goldsInHouse_; }
    set {
      goldsInHouse_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GameFinishedPlayer);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GameFinishedPlayer other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PlayerId != other.PlayerId) return false;
    if (Keys != other.Keys) return false;
    if (Golds != other.Golds) return false;
    if (GoldsInHouse != other.GoldsInHouse) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PlayerId.Length != 0) hash ^= PlayerId.GetHashCode();
    if (Keys != 0) hash ^= Keys.GetHashCode();
    if (Golds != 0) hash ^= Golds.GetHashCode();
    if (GoldsInHouse != 0) hash ^= GoldsInHouse.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PlayerId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(PlayerId);
    }
    if (Keys != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Keys);
    }
    if (Golds != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Golds);
    }
    if (GoldsInHouse != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(GoldsInHouse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PlayerId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(PlayerId);
    }
    if (Keys != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Keys);
    }
    if (Golds != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(Golds);
    }
    if (GoldsInHouse != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(GoldsInHouse);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PlayerId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PlayerId);
    }
    if (Keys != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Keys);
    }
    if (Golds != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Golds);
    }
    if (GoldsInHouse != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GoldsInHouse);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GameFinishedPlayer other) {
    if (other == null) {
      return;
    }
    if (other.PlayerId.Length != 0) {
      PlayerId = other.PlayerId;
    }
    if (other.Keys != 0) {
      Keys = other.Keys;
    }
    if (other.Golds != 0) {
      Golds = other.Golds;
    }
    if (other.GoldsInHouse != 0) {
      GoldsInHouse = other.GoldsInHouse;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          PlayerId = input.ReadString();
          break;
        }
        case 16: {
          Keys = input.ReadUInt32();
          break;
        }
        case 24: {
          Golds = input.ReadUInt32();
          break;
        }
        case 32: {
          GoldsInHouse = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          PlayerId = input.ReadString();
          break;
        }
        case 16: {
          Keys = input.ReadUInt32();
          break;
        }
        case 24: {
          Golds = input.ReadUInt32();
          break;
        }
        case 32: {
          GoldsInHouse = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class GameFinishedMessage : pb::IMessage<GameFinishedMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GameFinishedMessage> _parser = new pb::MessageParser<GameFinishedMessage>(() => new GameFinishedMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GameFinishedMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameFinishedMessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameFinishedMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameFinishedMessage(GameFinishedMessage other) : this() {
    roundCount_ = other.roundCount_;
    rank_ = other.rank_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GameFinishedMessage Clone() {
    return new GameFinishedMessage(this);
  }

  /// <summary>Field number for the "round_count" field.</summary>
  public const int RoundCountFieldNumber = 1;
  private uint roundCount_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RoundCount {
    get { return roundCount_; }
    set {
      roundCount_ = value;
    }
  }

  /// <summary>Field number for the "rank" field.</summary>
  public const int RankFieldNumber = 2;
  private static readonly pb::FieldCodec<global::GameFinishedPlayer> _repeated_rank_codec
      = pb::FieldCodec.ForMessage(18, global::GameFinishedPlayer.Parser);
  private readonly pbc::RepeatedField<global::GameFinishedPlayer> rank_ = new pbc::RepeatedField<global::GameFinishedPlayer>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::GameFinishedPlayer> Rank {
    get { return rank_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GameFinishedMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GameFinishedMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RoundCount != other.RoundCount) return false;
    if(!rank_.Equals(other.rank_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RoundCount != 0) hash ^= RoundCount.GetHashCode();
    hash ^= rank_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RoundCount != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(RoundCount);
    }
    rank_.WriteTo(output, _repeated_rank_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RoundCount != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(RoundCount);
    }
    rank_.WriteTo(ref output, _repeated_rank_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RoundCount != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RoundCount);
    }
    size += rank_.CalculateSize(_repeated_rank_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GameFinishedMessage other) {
    if (other == null) {
      return;
    }
    if (other.RoundCount != 0) {
      RoundCount = other.RoundCount;
    }
    rank_.Add(other.rank_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RoundCount = input.ReadUInt32();
          break;
        }
        case 18: {
          rank_.AddEntriesFrom(input, _repeated_rank_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RoundCount = input.ReadUInt32();
          break;
        }
        case 18: {
          rank_.AddEntriesFrom(ref input, _repeated_rank_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
