// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Inventory.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Inventory.proto</summary>
public static partial class InventoryReflection {

  #region Descriptor
  /// <summary>File descriptor for Inventory.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static InventoryReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9JbnZlbnRvcnkucHJvdG8ibQoJSW52ZW50b3J5EgwKBGtleXMYASABKA0S",
          "DgoGbW9uZXlzGAIgASgNEhUKDXJlbWFpbmVkX3BlZWsYAyABKA0SEAoIaG91",
          "c2VfaWQYBCABKAkSGQoRaG91c2VfY29vcmRfaW5kZXgYBSABKARiBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Inventory), global::Inventory.Parser, new[]{ "Keys", "Moneys", "RemainedPeek", "HouseId", "HouseCoordIndex" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Inventory : pb::IMessage<Inventory>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Inventory> _parser = new pb::MessageParser<Inventory>(() => new Inventory());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Inventory> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::InventoryReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Inventory() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Inventory(Inventory other) : this() {
    keys_ = other.keys_;
    moneys_ = other.moneys_;
    remainedPeek_ = other.remainedPeek_;
    houseId_ = other.houseId_;
    houseCoordIndex_ = other.houseCoordIndex_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Inventory Clone() {
    return new Inventory(this);
  }

  /// <summary>Field number for the "keys" field.</summary>
  public const int KeysFieldNumber = 1;
  private uint keys_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Keys {
    get { return keys_; }
    set {
      keys_ = value;
    }
  }

  /// <summary>Field number for the "moneys" field.</summary>
  public const int MoneysFieldNumber = 2;
  private uint moneys_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Moneys {
    get { return moneys_; }
    set {
      moneys_ = value;
    }
  }

  /// <summary>Field number for the "remained_peek" field.</summary>
  public const int RemainedPeekFieldNumber = 3;
  private uint remainedPeek_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RemainedPeek {
    get { return remainedPeek_; }
    set {
      remainedPeek_ = value;
    }
  }

  /// <summary>Field number for the "house_id" field.</summary>
  public const int HouseIdFieldNumber = 4;
  private string houseId_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HouseId {
    get { return houseId_; }
    set {
      houseId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "house_coord_index" field.</summary>
  public const int HouseCoordIndexFieldNumber = 5;
  private ulong houseCoordIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong HouseCoordIndex {
    get { return houseCoordIndex_; }
    set {
      houseCoordIndex_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Inventory);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Inventory other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Keys != other.Keys) return false;
    if (Moneys != other.Moneys) return false;
    if (RemainedPeek != other.RemainedPeek) return false;
    if (HouseId != other.HouseId) return false;
    if (HouseCoordIndex != other.HouseCoordIndex) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Keys != 0) hash ^= Keys.GetHashCode();
    if (Moneys != 0) hash ^= Moneys.GetHashCode();
    if (RemainedPeek != 0) hash ^= RemainedPeek.GetHashCode();
    if (HouseId.Length != 0) hash ^= HouseId.GetHashCode();
    if (HouseCoordIndex != 0UL) hash ^= HouseCoordIndex.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Keys != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Keys);
    }
    if (Moneys != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Moneys);
    }
    if (RemainedPeek != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(RemainedPeek);
    }
    if (HouseId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(HouseId);
    }
    if (HouseCoordIndex != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(HouseCoordIndex);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Keys != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Keys);
    }
    if (Moneys != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Moneys);
    }
    if (RemainedPeek != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(RemainedPeek);
    }
    if (HouseId.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(HouseId);
    }
    if (HouseCoordIndex != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(HouseCoordIndex);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Keys != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Keys);
    }
    if (Moneys != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Moneys);
    }
    if (RemainedPeek != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RemainedPeek);
    }
    if (HouseId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HouseId);
    }
    if (HouseCoordIndex != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(HouseCoordIndex);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Inventory other) {
    if (other == null) {
      return;
    }
    if (other.Keys != 0) {
      Keys = other.Keys;
    }
    if (other.Moneys != 0) {
      Moneys = other.Moneys;
    }
    if (other.RemainedPeek != 0) {
      RemainedPeek = other.RemainedPeek;
    }
    if (other.HouseId.Length != 0) {
      HouseId = other.HouseId;
    }
    if (other.HouseCoordIndex != 0UL) {
      HouseCoordIndex = other.HouseCoordIndex;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Keys = input.ReadUInt32();
          break;
        }
        case 16: {
          Moneys = input.ReadUInt32();
          break;
        }
        case 24: {
          RemainedPeek = input.ReadUInt32();
          break;
        }
        case 34: {
          HouseId = input.ReadString();
          break;
        }
        case 40: {
          HouseCoordIndex = input.ReadUInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Keys = input.ReadUInt32();
          break;
        }
        case 16: {
          Moneys = input.ReadUInt32();
          break;
        }
        case 24: {
          RemainedPeek = input.ReadUInt32();
          break;
        }
        case 34: {
          HouseId = input.ReadString();
          break;
        }
        case 40: {
          HouseCoordIndex = input.ReadUInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
