// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServerConfigModel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ServerConfigModel.proto</summary>
public static partial class ServerConfigModelReflection {

  #region Descriptor
  /// <summary>File descriptor for ServerConfigModel.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ServerConfigModelReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdTZXJ2ZXJDb25maWdNb2RlbC5wcm90byK3AQoRU2VydmVyQ29uZmlnTW9k",
          "ZWwSFAoMaW5pdGlhbF9rZXlzGAEgASgNEhUKDWluaXRpYWxfZ29sZHMYAiAB",
          "KA0SGwoTaW5pdGlhbF9ob3VzZV9nb2xkcxgDIAEoDRIbChNpbml0aWFsX3Bl",
          "ZWtfY2hhbmNlGAQgASgNEhUKDWZpbmlzaF9yb3VuZHMYBSABKA0SJAocYm90",
          "c19zdGF5c19hdF9ob21lX3RocmVzaG9sZBgGIAEoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ServerConfigModel), global::ServerConfigModel.Parser, new[]{ "InitialKeys", "InitialGolds", "InitialHouseGolds", "InitialPeekChance", "FinishRounds", "BotsStaysAtHomeThreshold" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ServerConfigModel : pb::IMessage<ServerConfigModel>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ServerConfigModel> _parser = new pb::MessageParser<ServerConfigModel>(() => new ServerConfigModel());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ServerConfigModel> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ServerConfigModelReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerConfigModel() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerConfigModel(ServerConfigModel other) : this() {
    initialKeys_ = other.initialKeys_;
    initialGolds_ = other.initialGolds_;
    initialHouseGolds_ = other.initialHouseGolds_;
    initialPeekChance_ = other.initialPeekChance_;
    finishRounds_ = other.finishRounds_;
    botsStaysAtHomeThreshold_ = other.botsStaysAtHomeThreshold_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ServerConfigModel Clone() {
    return new ServerConfigModel(this);
  }

  /// <summary>Field number for the "initial_keys" field.</summary>
  public const int InitialKeysFieldNumber = 1;
  private uint initialKeys_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint InitialKeys {
    get { return initialKeys_; }
    set {
      initialKeys_ = value;
    }
  }

  /// <summary>Field number for the "initial_golds" field.</summary>
  public const int InitialGoldsFieldNumber = 2;
  private uint initialGolds_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint InitialGolds {
    get { return initialGolds_; }
    set {
      initialGolds_ = value;
    }
  }

  /// <summary>Field number for the "initial_house_golds" field.</summary>
  public const int InitialHouseGoldsFieldNumber = 3;
  private uint initialHouseGolds_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint InitialHouseGolds {
    get { return initialHouseGolds_; }
    set {
      initialHouseGolds_ = value;
    }
  }

  /// <summary>Field number for the "initial_peek_chance" field.</summary>
  public const int InitialPeekChanceFieldNumber = 4;
  private uint initialPeekChance_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint InitialPeekChance {
    get { return initialPeekChance_; }
    set {
      initialPeekChance_ = value;
    }
  }

  /// <summary>Field number for the "finish_rounds" field.</summary>
  public const int FinishRoundsFieldNumber = 5;
  private uint finishRounds_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint FinishRounds {
    get { return finishRounds_; }
    set {
      finishRounds_ = value;
    }
  }

  /// <summary>Field number for the "bots_stays_at_home_threshold" field.</summary>
  public const int BotsStaysAtHomeThresholdFieldNumber = 6;
  private uint botsStaysAtHomeThreshold_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint BotsStaysAtHomeThreshold {
    get { return botsStaysAtHomeThreshold_; }
    set {
      botsStaysAtHomeThreshold_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ServerConfigModel);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ServerConfigModel other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (InitialKeys != other.InitialKeys) return false;
    if (InitialGolds != other.InitialGolds) return false;
    if (InitialHouseGolds != other.InitialHouseGolds) return false;
    if (InitialPeekChance != other.InitialPeekChance) return false;
    if (FinishRounds != other.FinishRounds) return false;
    if (BotsStaysAtHomeThreshold != other.BotsStaysAtHomeThreshold) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (InitialKeys != 0) hash ^= InitialKeys.GetHashCode();
    if (InitialGolds != 0) hash ^= InitialGolds.GetHashCode();
    if (InitialHouseGolds != 0) hash ^= InitialHouseGolds.GetHashCode();
    if (InitialPeekChance != 0) hash ^= InitialPeekChance.GetHashCode();
    if (FinishRounds != 0) hash ^= FinishRounds.GetHashCode();
    if (BotsStaysAtHomeThreshold != 0) hash ^= BotsStaysAtHomeThreshold.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (InitialKeys != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(InitialKeys);
    }
    if (InitialGolds != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(InitialGolds);
    }
    if (InitialHouseGolds != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(InitialHouseGolds);
    }
    if (InitialPeekChance != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(InitialPeekChance);
    }
    if (FinishRounds != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(FinishRounds);
    }
    if (BotsStaysAtHomeThreshold != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(BotsStaysAtHomeThreshold);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (InitialKeys != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(InitialKeys);
    }
    if (InitialGolds != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(InitialGolds);
    }
    if (InitialHouseGolds != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(InitialHouseGolds);
    }
    if (InitialPeekChance != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(InitialPeekChance);
    }
    if (FinishRounds != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(FinishRounds);
    }
    if (BotsStaysAtHomeThreshold != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(BotsStaysAtHomeThreshold);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (InitialKeys != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InitialKeys);
    }
    if (InitialGolds != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InitialGolds);
    }
    if (InitialHouseGolds != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InitialHouseGolds);
    }
    if (InitialPeekChance != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InitialPeekChance);
    }
    if (FinishRounds != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FinishRounds);
    }
    if (BotsStaysAtHomeThreshold != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BotsStaysAtHomeThreshold);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ServerConfigModel other) {
    if (other == null) {
      return;
    }
    if (other.InitialKeys != 0) {
      InitialKeys = other.InitialKeys;
    }
    if (other.InitialGolds != 0) {
      InitialGolds = other.InitialGolds;
    }
    if (other.InitialHouseGolds != 0) {
      InitialHouseGolds = other.InitialHouseGolds;
    }
    if (other.InitialPeekChance != 0) {
      InitialPeekChance = other.InitialPeekChance;
    }
    if (other.FinishRounds != 0) {
      FinishRounds = other.FinishRounds;
    }
    if (other.BotsStaysAtHomeThreshold != 0) {
      BotsStaysAtHomeThreshold = other.BotsStaysAtHomeThreshold;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          InitialKeys = input.ReadUInt32();
          break;
        }
        case 16: {
          InitialGolds = input.ReadUInt32();
          break;
        }
        case 24: {
          InitialHouseGolds = input.ReadUInt32();
          break;
        }
        case 32: {
          InitialPeekChance = input.ReadUInt32();
          break;
        }
        case 40: {
          FinishRounds = input.ReadUInt32();
          break;
        }
        case 48: {
          BotsStaysAtHomeThreshold = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          InitialKeys = input.ReadUInt32();
          break;
        }
        case 16: {
          InitialGolds = input.ReadUInt32();
          break;
        }
        case 24: {
          InitialHouseGolds = input.ReadUInt32();
          break;
        }
        case 32: {
          InitialPeekChance = input.ReadUInt32();
          break;
        }
        case 40: {
          FinishRounds = input.ReadUInt32();
          break;
        }
        case 48: {
          BotsStaysAtHomeThreshold = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
